---
title: "§ 4 Das Robert Koch-Institut"
---

[Hier geht es zum § 4](https://www.gesetze-im-internet.de/ifsg/__4.html)

## Gesetzesauszug

> (1) Das Robert Koch-Institut ist die nationale Behörde zur Vorbeugung übertragbarer Krankheiten sowie zur frühzeitigen Erkennung und Verhinderung der Weiterverbreitung von Infektionen. Dies schließt die [...] Forschung [...] ein.


> (2) Das Robert Koch-Institut  erstellt im Benehmen mit den jeweils zuständigen Bundesbehörden __für Fachkreise__ [...], __Empfehlungen__, Merkblätter und sonstige Informationen

> (3) Das Robert Koch-Institut arbeitet zu den in § 1 Absatz 1 genannten Zwecken mit ausländischen Stellen und supranationalen Organisationen sowie mit der Weltgesundheitsorganisation und anderen internationalen Organisationen zusammen.

## Bemerkenswerte Punkte

* Im § 4 wird das Robert Koch-Institut verankert.
* Das RKI ist "Ressortforschungseinrichtung" -> Das erlaubt Forschung und Wissenschaftsfreiheit 
* Das RKI arbeitet (fachlich) mit den anderen Bundesoberbehörden zusammen (und nicht mit dem BMG) 
* __Obersten__ Landesgesundheitsbehörde können Amtshilfe beantragen
* Arbeit __für Fachkreise__
* Das RKI arbeitet auch international
