---
title: "§ 34 Kindereinrichtungen"
---

[Hier geht es zum § 34](https://www.gesetze-im-internet.de/ifsg/__34.html)

## Gesetzesauszug
> Personen die an [_Auflistung mehrere Krankheiten_] erkrankt oder dessen verdächtig oder die verlaust sind, dürfen in den in § 33 genannten Gemeinschaftseinrichtungen keine Lehr-, Erziehungs-, Pflege-, Aufsichts- oder sonstige Tätigkeiten ausüben

## Bemerkenswerte Punkte

* Absatz ist wichtig für die Arbeit im Gesundheitsamt
* Es gibt eine Unterteilung nach Erkrankten, Ausscheidern und Mitbewohnende
* Gesetz gilt auch ohne Anordnung des Gesundheitsamtes
* Belehrungspflicht und Benachrichtigungspflicht
* Impfaufklärung (Einführung vor Impfpflicht)

## Beispiel

::: {.panel-tabset}

## Beispielproblem
Shigelloseausbruch
Einer Hygienekontrolleurin fällt auf, dass sie heute zwei Shigellose-Fälle hat, die nicht aus dem Ausland kommen. Es stellt sich heraus, das es einige Fälle in einer Kita gibt. 


## Was haben wir getan?
* Vor Ort ermittelt
* VetLeb informiert
* Die Landesstelle gefragt, ob uns jemand unterstützen will
* Andere Kitas des Caterers Stuhlproben 
* Kontaktdaten, Linelist 
* Ausbruchsfalldefinition festgelegt
* TVs nach [Wiederzulassungstabelle §34](https://www.rki.de/DE/Content/Infekt/EpidBull/Merkblaetter/Wiederzulassung/Wiederzulassung_Tabelle.pdf?__blob=publicationFile) angesetzt
* Aushang und Informationsweitergabe durch die Kitaleitung (FAQ durch uns) 
* <a href="{{ site.url }}{{ site.baseurl }}/assets/2022-01-31-IfSG-WBK/shigellenausbruch.pdf">Anordnung Shigellenausbruch</a>
* Keine Suche nach Personen mit riskantem Sexualverhalten 

:::


