---
title: "§ 23 Hygieneparagraph"
---

[Hier geht es zum § 23](https://www.gesetze-im-internet.de/ifsg/__23.html)

## Gesetzesauszug
> Die Leiter folgender Einrichtungen haben sicherzustellen, dass die nach dem Stand der medizinischen Wissenschaft erforderlichen Maßnahmen getroffen werden, um nosokomiale Infektionen zu verhüten und die Weiterverbreitung von Krankheitserregern [...] zu vermeiden: 

## Bemerkenswerte Punkte

* Hiermit kommen die KRINKO-Empfehlungen in die Welt
* Der __Stand der medizinischen Wissenschaft__ ist ziemlich tiefgreifend und geht z.B. über den Stand von __Technik__ hinaus.
* Die ART-Kommission wird hier gegründet
* Der Artikel hilft (bedingt) bei einer Begehung als Verpflichtung
* Gesundheitsämter sind selber auch betroffen in (3) Punkt 10
* Die Länder können und machen aufgrund dieses Paragraphen wichtig Rechtsverordnungen

## Beispiel

::: {.panel-tabset}
## Beispielproblem
Ein Krankenhaus hat nicht genügend Hygienepersonal.

## Herangehensweise
* Ansprechen bei der Begehung
* Anordnung der Erfassung des nach [KRINKO](https://www.rki.de/DE/Content/Infekt/Krankenhaushygiene/Kommission/kommission_node.html/) notwendigen Personals
* Einfacher durchzusetzen wäre die [Hygieneverordnung](https://www.aekb.de/fileadmin/migration/pdf/Anlage_1_Hygieneverordnung_Berlin_12_06_2012.pdf) 
:::
