---
title: "§ 6 Die Arztmeldepflicht"
---

[Hier geht es zum § 6](https://www.gesetze-im-internet.de/ifsg/__6.html)

## Gesetzesauszug
> Namentlich ist zu melden: der Verdacht einer Erkrankung, die Erkrankung sowie der Tod

> Die Erkrankung und der Tod in Bezug auf folgende Krankheiten: behandlungsbedürftige Tuberkulose [...],     Clostridioides-difficile-Infektion mit klinisch schwerem Verlauf

> Der Verdacht auf und die Erkrankung an einer mikrobiell bedingten Lebensmittelvergiftung

> Der Verdacht einer [UAW bei Impfungen]

> Die Verletzung eines Menschen durch [...] Tollwut

> Der Verdacht einer Erkrankung, die Erkrankung sowie der Tod, in Bezug auf eine bedrohliche übertragbare Krankheit, die nicht bereits nach den Nummern 1 bis 4 meldepflichtig ist.

## Bemerkenswerte Punkte

* Hier gibt es die verschiedenen Meldetatbestände
  * _Verdacht, Krankheit, Tod_ von bestimmten Krankheiten 
  * Lebensmittelvergiftung
  * Impfnebenwirkung
  * Sonstige bedrohliche Krankheit
  * Nosokomiale Krankheiten
* Besonderheiten bei bestimmten Krankheiten
  * Nur bestimmte Clostridioides-Fälle
  * SSPE
  * Tuberkulose-Verweigerung
  * Tollwut auch bei Berührung
* Covid-19 ist auch bei Verdacht meldepflichtig -> Fachlich nicht sinnvoll
* Nichtnamentliche Meldepflicht bei Ausbrüchen -> Verursacht gewaltige Komplexitäten